### PR TITLE
Format code using 'cargo fmt'

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by chrissimpkins** [comment]
I'm in favor of this but found the code without fmt applied so didn't touch it.  This means that I have to avoid the editors with autofmt'ing config'd. :)

**Comment by chrissimpkins** [comment]
@Mark-Simulacrum @pnkfelix @spastorino Thoughts about fmt on this project?  

Associated #73

**Comment by Mark-Simulacrum** [comment]
I'm in favor; I don't have time to review PRs etc though.

**Comment by spastorino** [comment]
Pushed here https://github.com/rust-lang/cargo-bisect-rustc/commit/843b96ec3dfa26e7c7d51d3dd589c2f8f0705cae, preserved the author.

**Comment by chrissimpkins** [comment]
Thanks @Atul9!

**Pull request closed without merging**
