### PR TITLE
Include compiler crashes in ICE defintion

### PR DESCRIPTION
**Pull request by Alexendoo**
This matches the definition [used in glacier], which includes exit status
101 without an accompanying diagnostic (such as rust-lang/rust#21599), and when
rustc is killed by a signal (rust-lang/rust#13368)

This also means no processing modes are capturing stdio, but I didn't
remove it as it may be desired for the regex features discussed in #53

[used in glacier]: https://github.com/rust-lang/glacier/blob/77029d8e7f755bd95913d3c741738674d5ccadc3/src/lib.rs#L51-L56

### CODE REVIEW

**Comment by pnkfelix** [comment]
I don't think this PR was quite right; it treats error code 101 as a unique identifier for ICE's, but even normal static errors from `rustc` will produce that same error code, I believe.

This mistake ends up breaking certain uses of `--regress=ice`, such as one I'm trying to include in my test suite as part of PR #88.

I'm going to revert this PR as part of PR #88 and open an issue to re-add its effects in a manner compatible with `--regress=ice`

**Comment by pnkfelix** [comment]
I do see that Glacier *is* [using this same logic](https://github.com/rust-lang/glacier/blob/77029d8e7f755bd95913d3c741738674d5ccadc3/src/lib.rs#L51-L56) (link taken from commit). So either I'm wrong or glacier is wrong. Hmm.

**Comment by pnkfelix** [comment]
Ah, Glacier invokes `rustc` directly. So maybe Glacier's logic is correct for direct `rustc` invocations, but not appropriate for `cargo` invocations?

**Comment by Alexendoo** [comment]
Ah yeah sorry I didn't test cargo directly, I was using it with `--script rustc -- file` and assumed it would be the same

**Pull request merged**
