### PR TITLE
Properly report the scanned date

### LINKED ISSUE #82: Searched date range misreported
https://github.com/bjorn3/cargo-bisect-rustc-bot-jobs/runs/650650115#step:6:107

I told cargo bisect-rustc to bisect up to 2020-04-25 and it did that, but in the final report it said that it bisected up to 2020-04-10

### PR DESCRIPTION
**Pull request by spastorino**
Closes #82 

I believe this should close #82 but didn't have time to properly test this. cc @bjorn3

### CODE REVIEW

**Comment by bjorn3** [comment]
https://github.com/bjorn3/cargo-bisect-rustc-bot-jobs/runs/658994854#step:6:60

>  thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 5', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2791:10

**Comment by spastorino** [comment]
Ahh right, this https://github.com/spastorino/cargo-bisect-rustc/blob/6bbdf9696cf4a68219476bbd12967a3a9f4c3142/src/main.rs#L975 is using `&toolchains` instead of `&searched_toolchains`, so it's returning an index to `&toolchains` and searching on `&searched_toolchains` still we doesn't seem to just want to change that because that call also installs and test. We would need to review a bit better what that function is doing and provide a proper fix for this.

**Comment by spastorino** [comment]
@bjorn3 just cloned your repo and test it ...

Now I get this ...

```
searched toolchains nightly-2020-04-03 through nightly-2020-04-25


********************************************************************************
Regression in nightly-2020-04-08
********************************************************************************
```

which is correct.
Anyway, feel free to test this out and let me know.

**Comment by chrissimpkins** [comment]
Happy to take a look.  Can you point to the source that you are testing in #82 @bjorn3?

**Comment by bjorn3** [comment]
https://github.com/bjorn3/cargo-bisect-rustc-bot-jobs/tree/job-gh624833148

**Comment by chrissimpkins** [comment]
As of 8ba5cab2b409773baf0b282fc2a4c86d11658060, I am still seeing the error in the final report "searched nightlies" line:

```
********************************************************************************
Regression in 209b2be09fcaff937480d1fbbe8b31646e361c7a
********************************************************************************

==================================================================================
= Please open an issue on Rust's github repository                               =
= https://github.com/rust-lang/rust/issues/new                                   =
= Below you will find a text that would serve as a starting point of your report =
==================================================================================

# Regression found in the compiler

searched nightlies: from nightly-2020-04-03 to nightly-2020-04-10
regressed nightly: nightly-2020-04-08
searched commits: from https://github.com/rust-lang/rust/commit/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257 to https://github.com/rust-lang/rust/commit/42abbd8878d3b67238f3611b0587c704ba94f39c
regressed commit: https://github.com/rust-lang/rust/commit/209b2be09fcaff937480d1fbbe8b31646e361c7a
source code: URL OF A REPOSITORY THAT REPRODUCES THE ERROR
```

I'll have a more detailed look at the source tomorrow.

**Comment by chrissimpkins** [comment]
I think that I identified the issue.  I'll push a commit tomorrow with the changes.

**Comment by spastorino** [comment]
Doh, I didn't see that the last part of the report had that issue too. Fixed it now, but it seems that we may want to organize our code a bit better :).

**Comment by chrissimpkins** [comment]
Yep! That was it.  But I did find that there seems to be a new issue with these changes.  Now the commits report line is the following:

```
searched toolchains 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257 through nightly-2020-04-25
```

I'll let you know if I track it down.

**Comment by chrissimpkins** [comment]
And FWIW, I think that the original problem arose because the "end date" is redefined during the iterative checks for bounds when the `--end` flag is used without a `--start` definition.  If I am understanding this correctly, it happens here:

https://github.com/rust-lang/cargo-bisect-rustc/blob/6e4dbe95ffd2b7cac0af53b3803a5434613bb5d2/src/main.rs#L918

**Comment by spastorino** [comment]
This is messy :). So the problem is not related to `last_failure` being mutable. The problem is that I forgot we were calling `report_result` for Ci toolchains when cfg.is_commit is false.

With this new attempt I get ...

```
[santiago@galago cargo-bisect-rustc-bot-jobs (job-gh624833148)]$ ~/src/oss/cargo-bisect-rustc/target/debug/cargo-bisect-rustc "--end=2020-04-25" --access=github --preserve
installing nightly-2020-04-25
testing...
RESULT: nightly-2020-04-25, ===> Yes

installing nightly-2020-04-23
testing...
RESULT: nightly-2020-04-23, ===> Yes

installing nightly-2020-04-21
testing...
RESULT: nightly-2020-04-21, ===> Yes

installing nightly-2020-04-19
testing...
RESULT: nightly-2020-04-19, ===> Yes

installing nightly-2020-04-17
testing...
RESULT: nightly-2020-04-17, ===> Yes

installing nightly-2020-04-10
testing...
RESULT: nightly-2020-04-10, ===> Yes

installing nightly-2020-04-03
testing...
RESULT: nightly-2020-04-03, ===> No

installing nightly-2020-04-10
testing...
RESULT: nightly-2020-04-10, ===> Yes

installing nightly-2020-04-06
testing...
RESULT: nightly-2020-04-06, ===> No

installing nightly-2020-04-08
testing...
RESULT: nightly-2020-04-08, ===> Yes

installing nightly-2020-04-07
testing...
RESULT: nightly-2020-04-07, ===> No

searched toolchains nightly-2020-04-03 through nightly-2020-04-25


********************************************************************************
Regression in nightly-2020-04-08
********************************************************************************

fetching https://static.rust-lang.org/dist/2020-04-08/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2020-04-08: 40 B / 40 B [===============================================================================================================================================================================] 100.00 % 5.39 KB/s converted 2020-04-08 to 42abbd8878d3b67238f3611b0587c704ba94f39c
fetching https://static.rust-lang.org/dist/2020-04-07/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2020-04-07: 40 B / 40 B [===============================================================================================================================================================================] 100.00 % 9.92 KB/s converted 2020-04-07 to 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257
looking for regression commit between 2020-04-08 and 2020-04-07
fetching (via remote github) commits from max(6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257, 2020-04-05UTC) to 42abbd8878d3b67238f3611b0587c704ba94f39c
ending github query because we found starting sha: 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257
get_commits_between returning commits, len: 5
  commit[0] 2020-04-06UTC: Auto merge of #70573 - IgorPerikov:issue#70524_detailed_panic_messages, r=LukasKalbertodt
  commit[1] 2020-04-07UTC: Auto merge of #70865 - Dylan-DPC:rollup-jje2cuv, r=Dylan-DPC
  commit[2] 2020-04-07UTC: Auto merge of #70164 - eddyb:walk-generic-arg, r=nikomatsakis
  commit[3] 2020-04-07UTC: Auto merge of #70837 - nnethercote:speed-up-find_library_crate, r=petrochenkov
  commit[4] 2020-04-07UTC: Auto merge of #70884 - Dylan-DPC:rollup-r3raqdf, r=jonas-schievink
validated commits found, specifying toolchains

installing 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257
testing...
RESULT: 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257, ===> No

installing 42abbd8878d3b67238f3611b0587c704ba94f39c
testing...
RESULT: 42abbd8878d3b67238f3611b0587c704ba94f39c, ===> Yes

installing 209b2be09fcaff937480d1fbbe8b31646e361c7a
testing...
RESULT: 209b2be09fcaff937480d1fbbe8b31646e361c7a, ===> Yes

installing bf1f2eedda4fa02b7c9347dd849ed73ddd43dedc
testing...
RESULT: bf1f2eedda4fa02b7c9347dd849ed73ddd43dedc, ===> No

searched toolchains 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257 through 42abbd8878d3b67238f3611b0587c704ba94f39c


********************************************************************************
Regression in 209b2be09fcaff937480d1fbbe8b31646e361c7a
********************************************************************************

==================================================================================
= Please open an issue on Rust's github repository                               =
= https://github.com/rust-lang/rust/issues/new                                   =
= Below you will find a text that would serve as a starting point of your report =
==================================================================================

# Regression found in the compiler

searched nightlies: from nightly-2020-04-03 to nightly-2020-04-25
regressed nightly: nightly-2020-04-08
searched commits: from https://github.com/rust-lang/rust/commit/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257 to https://github.com/rust-lang/rust/commit/42abbd8878d3b67238f3611b0587c704ba94f39c
regressed commit: https://github.com/rust-lang/rust/commit/209b2be09fcaff937480d1fbbe8b31646e361c7a
source code: URL OF A REPOSITORY THAT REPRODUCES THE ERROR

## Instructions

Please give the steps for how to build your repository (platform, system dependencies, etc.)
## Error

<details><summary>COLLAPSIBLE ERROR STACKTRACE</summary>
<p>

Paste the error the compiler is giving

</p></details>
``` 

Have checked it bit by bit and seems right now.

**Comment by spastorino** [comment]
Meanwhile we are at this ...

```
looking for regression commit between 2020-04-08 and 2020-04-07
```

Seems backwards to me, I'd go with ...

```
looking for regression commit between 2020-04-07 and 2020-04-08
```
Most of the time we first print the start and then the end, not the other way around.

**Comment by spastorino** [comment]
Fixed more little bits about the formatting and this is the final result ...

```
[santiago@galago cargo-bisect-rustc-bot-jobs (job-gh624833148)]$ ~/src/oss/cargo-bisect-rustc/target/debug/cargo-bisect-rustc "--end=2020-04-25" --access=github --preserve
installing nightly-2020-04-25
testing...
RESULT: nightly-2020-04-25, ===> Yes

installing nightly-2020-04-23
testing...
RESULT: nightly-2020-04-23, ===> Yes

installing nightly-2020-04-21
testing...
RESULT: nightly-2020-04-21, ===> Yes

installing nightly-2020-04-19
testing...
RESULT: nightly-2020-04-19, ===> Yes

installing nightly-2020-04-17
testing...
RESULT: nightly-2020-04-17, ===> Yes

installing nightly-2020-04-10
testing...
RESULT: nightly-2020-04-10, ===> Yes

installing nightly-2020-04-03
testing...
RESULT: nightly-2020-04-03, ===> No

installing nightly-2020-04-10
testing...
RESULT: nightly-2020-04-10, ===> Yes

installing nightly-2020-04-06
testing...
RESULT: nightly-2020-04-06, ===> No

installing nightly-2020-04-08
testing...
RESULT: nightly-2020-04-08, ===> Yes

installing nightly-2020-04-07
testing...
RESULT: nightly-2020-04-07, ===> No

searched toolchains nightly-2020-04-03 through nightly-2020-04-25


********************************************************************************
Regression in nightly-2020-04-08
********************************************************************************

fetching https://static.rust-lang.org/dist/2020-04-07/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2020-04-07: 40 B / 40 B [===============================================================================================================================================================================] 100.00 % 5.15 KB/s converted 2020-04-07 to 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257
fetching https://static.rust-lang.org/dist/2020-04-08/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2020-04-08: 40 B / 40 B [===============================================================================================================================================================================] 100.00 % 5.47 KB/s converted 2020-04-08 to 42abbd8878d3b67238f3611b0587c704ba94f39c
looking for regression commit between 2020-04-07 and 2020-04-08
fetching (via remote github) commits from max(6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257, 2020-04-05) to 42abbd8878d3b67238f3611b0587c704ba94f39c
ending github query because we found starting sha: 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257
get_commits_between returning commits, len: 5
  commit[0] 2020-04-06UTC: Auto merge of #70573 - IgorPerikov:issue#70524_detailed_panic_messages, r=LukasKalbertodt
  commit[1] 2020-04-07UTC: Auto merge of #70865 - Dylan-DPC:rollup-jje2cuv, r=Dylan-DPC
  commit[2] 2020-04-07UTC: Auto merge of #70164 - eddyb:walk-generic-arg, r=nikomatsakis
  commit[3] 2020-04-07UTC: Auto merge of #70837 - nnethercote:speed-up-find_library_crate, r=petrochenkov
  commit[4] 2020-04-07UTC: Auto merge of #70884 - Dylan-DPC:rollup-r3raqdf, r=jonas-schievink
validated commits found, specifying toolchains

installing 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257
testing...
RESULT: 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257, ===> No

installing 42abbd8878d3b67238f3611b0587c704ba94f39c
testing...
RESULT: 42abbd8878d3b67238f3611b0587c704ba94f39c, ===> Yes

installing 209b2be09fcaff937480d1fbbe8b31646e361c7a
testing...
RESULT: 209b2be09fcaff937480d1fbbe8b31646e361c7a, ===> Yes

installing bf1f2eedda4fa02b7c9347dd849ed73ddd43dedc
testing...
RESULT: bf1f2eedda4fa02b7c9347dd849ed73ddd43dedc, ===> No

searched toolchains 6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257 through 42abbd8878d3b67238f3611b0587c704ba94f39c


********************************************************************************
Regression in 209b2be09fcaff937480d1fbbe8b31646e361c7a
********************************************************************************

==================================================================================
= Please open an issue on Rust's github repository                               =
= https://github.com/rust-lang/rust/issues/new                                   =
= Below you will find a text that would serve as a starting point of your report =
==================================================================================

# Regression found in the compiler

searched nightlies: from nightly-2020-04-03 to nightly-2020-04-25
regressed nightly: nightly-2020-04-08
searched commits: from https://github.com/rust-lang/rust/commit/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257 to https://github.com/rust-lang/rust/commit/42abbd8878d3b67238f3611b0587c704ba94f39c
regressed commit: https://github.com/rust-lang/rust/commit/209b2be09fcaff937480d1fbbe8b31646e361c7a
source code: URL OF A REPOSITORY THAT REPRODUCES THE ERROR

## Instructions

Please give the steps for how to build your repository (platform, system dependencies, etc.)
## Error

<details><summary>COLLAPSIBLE ERROR STACKTRACE</summary>
<p>

Paste the error the compiler is giving

</p></details>
```

**Comment by chrissimpkins** [comment]
This is a *very* verbose tool. I wonder if it makes sense to simply drop some of the interim reporting once the validity is confirmed?

**Comment by chrissimpkins** [comment]
> So the problem is not related to last_failure being mutable.

Sorry, I meant the original problem posted in the IR.

**Comment by spastorino** [comment]
Indeed it's very verbose, I'd say let's move that discussion to a separate issue.
Also from the output we can see a non ideal thing too, like `nightly-2020-04-10` being checked 2 times.
This problem has shown a couple of things, that Indeed the tool is verbose, that it's doing more work than it should, that the code is a bit messy and we may want to do some cleanups and that we need a test suite :).

**Comment by chrissimpkins** [comment]
> This problem has shown a couple of things, that Indeed the tool is verbose, that it's doing more work than it should, that the code is a bit messy and we may want to do some cleanups and that we need a test suite :).

Agree, agree, agree, agree++!

**Comment by chrissimpkins** [comment]
@pnkfelix was working on a test suite recently.  It may be worth looking into what he has at this stage before we start from scratch.  I think that a once over refactor with testing / source coverage in mind would be worth the effort.

**Pull request merged**
